apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
  namespace: sn-labs-santos321lol
spec:
  description: Clean the workspace.
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        set -eu
        rm -rf "${PWD:?}"/* "${PWD}"/.[!.]* "${PWD}"/..?* || true

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
  namespace: sn-labs-santos321lol
spec:
  workspaces:
    - name: source
  params:
    - name: args
      type: string
      default: "-v --with-spec --spec-color --with-coverage --cover-package=app"
  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt -vv
        pip install nose coverage 
        nosetests $(params.args)

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flake8
  namespace: sn-labs-santos321lol
spec:
  workspaces:
    - name: source
  params:
    - name: path
      type: string
      default: "service"
    - name: args
      type: array
      default:
        - "--max-line-length=127"
        - "--statistics"
  steps:
    - name: lint
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt -vv
        pip install flake8
        flake8 $(params.path) --count --ignore=E201,E202,E203,E231,E302,E111,E501 --max-line-length=127 --statistics
        flake8 $(params.path) "${@}"

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
  namespace: sn-labs-santos321lol
spec:
  workspaces:
    - name: source
  params:
    - name: IMAGE               # final image tag
      type: string
    - name: DOCKERFILE          # Dockerfile path
      type: string
      default: ./Dockerfile
    - name: CONTEXT             # build context dir
      type: string
      default: .
  stepTemplate:
    securityContext:
      runAsUser: 0                 # root in-container (non-privileged)
      runAsNonRoot: false
      allowPrivilegeEscalation: false
  steps:
    - name: build
      image: quay.io/buildah/stable:v1
      workingDir: $(workspaces.source.path)
      env:
        - name: BUILDAH_ISOLATION
          value: chroot            # OpenShift-friendly isolation
        - name: XDG_RUNTIME_DIR
          value: /tmp
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail

        # Use VFS storage to avoid fuse/overlay issues under restricted SCC
        mkdir -p "${HOME}/.config/containers"
        printf '[storage]\ndriver = "vfs"\n' > "${HOME}/.config/containers/storage.conf"

        # Disable user-namespaces globally in the container
        mkdir -p /etc/containers
        printf '[containers]\nuserns="host"\n' > /etc/containers/containers.conf

        # Build
        buildah bud \
          --userns=host \
          -f "$(params.DOCKERFILE)" \
          -t "$(params.IMAGE)" \
          "$(params.CONTEXT)"

        # Push
        buildah push \
          --userns=host \
          "$(params.IMAGE)"
