
# ---------------------------
# cleanup
# ---------------------------
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
  namespace: sn-labs-santos321lol
spec:
  description: Clean the workspace.
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        set -eu
        rm -rf "${PWD:?}"/* "${PWD}"/.[!.]* "${PWD}"/..?* || true

---
# ---------------------------
# git-clone (expects workspace 'output' in the pipeline)
# ---------------------------
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
  namespace: sn-labs-santos321lol
spec:
  description: Clone a Git repository into the workspace.
  workspaces:
    - name: output
  params:
    - name: url
      type: string
  steps:
    - name: clone
      image: docker.io/alpine/git:latest
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        set -eux
        git init
        git remote add origin "$(params.url)"
        git fetch --depth=1 origin main || git fetch --depth=1 origin
        git checkout -f FETCH_HEAD

---
# ---------------------------
# flake8
# ---------------------------


rsion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flake8
  namespace: sn-labs-santos321lol
spec:
  workspaces:
    - name: source
  params:
    - name: path
      type: string
      default: "service"
    - name: args
      type: array
      default:
        - "--max-line-length=127"
        - "--statistics"
  steps:
    - name: lint
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      args:
        - "$(params.args[*])"
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt -vv
        pip install flake8
        flake8 "$(params.path)" --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 "$(params.path)" "$@"

---
# ---------------------------
# nose
# ---------------------------
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
  namespace: sn-labs-santos321lol
spec:
  description: Run nose unit tests with coverage and spec-style output.
  workspaces:
    - name: source
  params:
    - name: args
      type: string
      default: "-v --with-spec --spec-color --with-coverage --cover-package=app"
  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt -vv
        pip install nose coverage
        nosetests $(params.args)

---
# ---------------------------
# buildah (non-privileged root; chroot + vfs; disable userns)
# ---------------------------
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
  namespace: sn-labs-santos321lol
spec:
  description: |
    Build and push OCI image with Buildah under restricted SCC (non-privileged).
    Uses chroot isolation and VFS storage; disables user-namespaces.
  workspaces:
    - name: source
  params:
    - name: IMAGE
      type: string        # e.g., quay.io/sn-labs-santos321lol/myapp:latest
    - name: DOCKERFILE
      type: string
      default: ./Dockerfile
    - name: CONTEXT
      type: string
      default: .
  stepTemplate:
    securityContext:
      runAsUser: 0
      runAsNonRoot: false
      allowPrivilegeEscalation: false
  steps:
    - name: build
      image: quay.io/buildah/stable:v1
      workingDir: $(workspaces.source.path)
      env:
        - name: BUILDAH_ISOLATION
          value: chroot
        - name: XDG_RUNTIME_DIR
          value: /tmp
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail

        # Use VFS storage to avoid fuse/overlay issues under restricted SCC
        mkdir -p "${HOME}/.config/containers"
        printf '[storage]\ndriver = "vfs"\n' > "${HOME}/.config/containers/storage.conf"

        # Disable user-namespaces globally in the container
        mkdir -p /etc/containers
        printf '[containers]\nuserns="host"\n' > /etc/containers/containers.conf

        # Build
        buildah bud \
          --userns=host \
          -f "$(params.DOCKERFILE)" \
          -t "$(params.IMAGE)" \
          "$(params.CONTEXT)"

        # Push
        buildah push \
          --userns=host \
          "$(params.IMAGE)"

---
# ---------------------------
# openshift-client
# ---------------------------
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: openshift-client
  namespace: sn-labs-santos321lol
spec:
  description: Run 'oc' commands against the cluster.
  params:
    - name: SCRIPT
      type: string
      default: "oc help"
  steps:
    - name: oc
      image: quay.io/openshift/origin-cli:latest
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail
        # Execute user-provided script
        cat <<'EOF' | bash -eu
        $(params.SCRIPT)
        EOF
